const accountConstant = {
  SELECT_ACCOUNT: 'SELECT_ACCOUNT',
  LOAD_ACCOUNTS: 'LOAD_ACCOUNTS',
  UPDATE_FILTER_MEDIAS: 'UPDATE_FILTER_MEDIAS',
  SELECT_ACCOUNT_TO_COPY_RULE: 'SELECT_ACCOUNT_TO_COPY_RULE'
}

export default accountConstant
