const AdjustmentRuleScheduleConstant = {
  SET_VISIBLE_SCHEDULE_ADJUSTMENT: 'SET_VISIBLE_SCHEDULE_ADJUSTMENT',
  SAVE_SCHEDULE: 'SAVE_SCHEDULE_ADJUSTMENT',
  RESET_SCHEDULE: "RESET_SCHEDULE_ADJUSTMENT",
  DAYS_OF_WEEK: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY", "HOLIDAY"],
}

export default AdjustmentRuleScheduleConstant
