const commonConstant = {
  UNKNOWN_ERROR_CODE: 1,
  UNAUTHORIZED_ERROR_CODE: 401,
  FORBIDDEN_ERROR_CODE: 403,
  NOT_FOUND_CODE: 2,
  PERMISSION_DENIED_CODE: 5,
  SYSTEM_ERROR_URL: '/500.html',
  NOT_FOUND_PAGE_URL: '/404',
  LOGIN_PAGE_URL: '/login',
  HOME_PAGE_URL: '/',

  API_TYPE: {
    PREVIEW_TARGET_ACTION_PATH: "PREVIEW_TARGET_ACTION_PATH",
    PREVIEW_TARGET_ACTION_PATH_TEST: "PREVIEW_TARGET_ACTION_PATH_TEST",
    GET_COST: "GET_COST",
    PREVIEW_SEARCH_SCOPE: "PREVIEW_SEARCH_SCOPE",
    GET_CAMPAIGNS: "GET_CAMPAIGNS",
    GET_TOTAL_MIN_COST: "GET_TOTAL_MIN_COST",
    GET_ADSETS: "GET_ADSETS",
    GET_REPORTS: "GET_REPORTS"
  },

  MEDIA: {
    FACEBOOK: "FACEBOOK",
    NEWLINE: "NEW LINE",
    TWITTER: "TWITTER"
  },

  FORWARD_METHOD: {
    GET: "GET",
    POST: "POST"
  }
}

export default commonConstant
