const currencies = [
  { code: "DZD", offset: 100, symbol: "دج", name: "Algerian Dinar" },
  { code: "ARS", offset: 100, symbol: "$", name: "Argentine Peso" },
  { code: "AUD", offset: 100, symbol: "A$", name: "Australian Dollar" },
  { code: "BDT", offset: 100, symbol: "৳", name: "Bangladeshi Taka" },
  { code: "BOB", offset: 100, symbol: "Bs", name: "Bolivian Boliviano" },
  { code: "BRL", offset: 100, symbol: "R$", name: "Brazilian Real" },
  { code: "GBP", offset: 100, symbol: "£", name: "British Pound" },
  { code: "CAD", offset: 100, symbol: "C$", name: "Canadian Dollar" },
  { code: "CLP", offset: 1, symbol: "CLP$", name: "Chilean Peso" },
  { code: "CNY", offset: 100, symbol: "¥", name: "Chinese Yuan" },
  { code: "COP", offset: 1, symbol: "COL$", name: "Colombian Peso" },
  { code: "CRC", offset: 1, symbol: "₡", name: "Costa Rican Colon" },
  { code: "CZK", offset: 100, symbol: "Kč", name: "Czech Koruna" },
  { code: "DKK", offset: 100, symbol: "kr", name: "Danish Krone" },
  { code: "EGP", offset: 100, symbol: "£", name: "Egyptian Pound" },
  { code: "EUR", offset: 100, symbol: "€", name: "Euro" },
  { code: "GTQ", offset: 100, symbol: "Q", name: "Guatemalan Quetza" },
  { code: "HNL", offset: 100, symbol: "L", name: "Honduran Lempira" },
  { code: "HKD", offset: 100, symbol: "HK$", name: "Hong Kong Dollar" },
  { code: "HUF", offset: 1, symbol: "Ft", name: "Hungarian Forint" },
  { code: "ISK", offset: 1, symbol: "kr", name: "Iceland Krona" },
  { code: "INR", offset: 100, symbol: "₹ ", name: "Indian Rupee" },
  { code: "IDR", offset: 1, symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "ILS", offset: 100, symbol: "₪", name: "Israeli New Shekel" },
  { code: "JPY", offset: 1, symbol: "¥", name: "Japanese Yen" },
  { code: "KES", offset: 100, symbol: "KSh", name: "Kenyan Shilling" },
  { code: "KRW", offset: 1, symbol: "₩", name: "Korean Won" },
  { code: "MOP", offset: 100, symbol: "P", name: "Macau Patacas" },
  { code: "MYR", offset: 100, symbol: "RM", name: "Malaysian Ringgit" },
  { code: "MXN", offset: 100, symbol: "Mex$", name: "Mexican Peso" },
  { code: "NZD", offset: 100, symbol: "NZ$", name: "New Zealand Dollar" },
  { code: "NIO", offset: 100, symbol: "C$", name: "Nicaraguan Cordoba" },
  { code: "NGN", offset: 100, symbol: "₦", name: "Nigerian Naira" },
  { code: "NOK", offset: 100, symbol: "kr", name: "Norwegian Krone" },
  { code: "PKR", offset: 100, symbol: "₨", name: "Pakistani Rupee" },
  { code: "PYG", offset: 1, symbol: "₲", name: "Paraguayan Guarani" },
  { code: "PEN", offset: 100, symbol: "S/.", name: "Peruvian Nuevo Sol" },
  { code: "PHP", offset: 100, symbol: "₱", name: "Philippine Peso" },
  { code: "PLN", offset: 100, symbol: "zł", name: "Polish Zloty" },
  { code: "QAR", offset: 100, symbol: "ر.ق", name: "Qatari Rials" },
  { code: "RON", offset: 100, symbol: "L", name: "Romanian Leu" },
  { code: "RUB", offset: 100, symbol: "₽", name: "Russian Ruble" },
  { code: "SAR", offset: 100, symbol: "ر.س", name: "Saudi Arabian Riyal" },
  { code: "SGD", offset: 100, symbol: "S$", name: "Singapore Dollar" },
  { code: "ZAR", offset: 100, symbol: "R", name: "South African Rand" },
  { code: "SEK", offset: 100, symbol: "kr", name: "Swedish Krona" },
  { code: "CHF", offset: 100, symbol: "S₣", name: "Swiss Franc" },
  { code: "TWD", offset: 1, symbol: "NT$", name: "Taiwan Dollar" },
  { code: "THB", offset: 100, symbol: "฿", name: "Thai Baht" },
  { code: "TRY", offset: 100, symbol: "TRY", name: "Turkish Lira" },
  { code: "AED", offset: 100, symbol: "د.إ", name: "Uae Dirham" },
  { code: "USD", offset: 100, symbol: "$", name: "United States Dollar" },
  { code: "UYU", offset: 100, symbol: "$U", name: "Uruguay Peso" },
  { code: "VEF", offset: 100, symbol: "Bs.", name: "Venezuelan Bolivar" },
  { code: "VND", offset: 1, symbol: "₫", name: "Vietnamese Dong" }
];

export default currencies
