const modalConstant = {
  SHOW_INFO_POPUP: 'SHOW_INFO_POPUP',
  SHOW_ERROR_POPUP: 'SHOW_ERROR_POPUP',
  HIDE_POPUP: 'HIDE_POPUP',
  SHOW_CONFIRM: 'SHOW_CONFIRM',
  SHOW_CONFIRM_DELETE: 'SHOW_CONFIRM_DELETE',
  COPY_RULE_TO_OTHER_ACCOUNT: 'COPY_RULE_TO_OTHER_ACCOUNT'
}

export default modalConstant
