const p4fCampaignDataConstant = {
  GET_FB_CAMPAIGNS:"GET_FB_CAMPAIGNS",
  UPDATE_FB_CAMPAIGNS:"UPDATE_FB_CAMPAIGNS",
  UPDATE_COST_TODAY:"UPDATE_COST_TODAY",
  UPDATE_FB_TOTAL_MIN_COST:"UPDATE_FB_TOTAL_MIN_COST",
  RESET_COST_TODAY:"RESET_COST_TODAY",
  RESET_FB_TOTAL_MIN_COST:"RESET_FB_TOTAL_MIN_COST",
  DEFAULT_SPENDCAP_LOWER_LIMIT:{
    JPY: 10000,
    USD: 100,
    KRW: 10000
  },
  UPDATE_TABLE_DATA: "UPDATE_TABLE_DATA"
}

export default p4fCampaignDataConstant
