const ruleListConstant = {
  UPDATE_RULE_LIST: 'UPDATE_RULE_LIST',
  SHOW_RULE_LIST: 'SHOW_RULE_LIST',
  SET_SELECTED_RULE_INDEX: 'SET_SELECTED_RULE_INDEX',
  CHANGE_RULE_STATUS: 'CHANGE_RULE_STATUS',
  STATUS: {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED'
  }
}

export default ruleListConstant
