const p4YahooStdRuleConstant = {
  UPDATE_EDITED_CELL:"UPDATE_EDITED_CELL",
  RESET_EDITED_CELL:"RESET_EDITED_CELL",
  UPDATE_REPORTS:"UPDATE_REPORTS",
  UPDATE_REPORT_PERIOD:"UPDATE_REPORT_PERIOD",
  UPDATE_SETTING_RULE: "UPDATE_SETTING_RULE",
  RESET_SETTING_RULE: "RESET_SETTING_RULE",
  RESET_MINIMUM_LIMIT_VALUES: "RESET_MINIMUM_LIMIT_VALUES",
  VALUE_DEFAULT: {
    REPORT_PERIOD_DEFAULT: "30DAY",
    REFERENCE_PERIOD_NOT_SET: "未設定",
    REFERENCE_DAY_NOT_SET: "notSet",
    TARGET_CPA_NOT_SET: "",
    UPPER_LIMIT_NOT_SET: "",
    MINIMUM_LIMIT_NOT_SET: "",
  }
}

export default p4YahooStdRuleConstant
